### ISSUE TITLE
updated version?

### ISSUE THREAD

**Issue by harvanchik** [Dcbrownie/Armor-Trim-23w04a#1]
Do you have a resource pack and datapack that works in the latest version of Minecraft, 1.20.1?  It seems that this datapack version is outdated and doesn't work anymore.

**Comment by Dcbrownie** [comment]
The pack should still work for Minecraft 1.20.1 as there haven't been any changes in the data formats that are used in this datapack, but Minecraft will still warn against using datapacks and resourcepacks with an older version number than is listed in the pack.mcmeta files. Regardless, a patch has been issued to change these version numbers to remove the warning.

**Comment by harvanchik** [comment]
I see.  Thank you.
